#!/usr/bin/env bash
#
# rpi-setup.sh — Raspberry Pi initial setup for School Supply Inventory
#
# Installs all prerequisites (curl, unzip, rsync, Docker, Docker Compose,
# Nginx), creates the /opt/apps directory structure, and configures Nginx
# as a reverse proxy in front of the application containers.
#
# Usage:
#   curl -fsSL <raw-url>/scripts/rpi-setup.sh | sudo bash
#   — or —
#   sudo ./rpi-setup.sh
#
# Tested on: Raspberry Pi OS (Bookworm, 64-bit)
#
set -euo pipefail

# ──────────────────────────────────────────────
# Configuration
# ──────────────────────────────────────────────
INSTALL_DIR="/opt/apps/school-inventory"
BACKUP_DIR="/opt/apps/school-inventory-backups"
NGINX_CONF="/etc/nginx/sites-available/school-inventory"
NGINX_LINK="/etc/nginx/sites-enabled/school-inventory"

# ──────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────
log()  { echo -e "\033[1;34m[setup]\033[0m $*"; }
warn() { echo -e "\033[1;33m[warn]\033[0m $*"; }
err()  { echo -e "\033[1;31m[error]\033[0m $*" >&2; }
fail() { err "$@"; exit 1; }

require_root() {
    if [[ $EUID -ne 0 ]]; then
        fail "This script must be run as root (sudo)."
    fi
}

# ──────────────────────────────────────────────
# Step 1 — System packages
# ──────────────────────────────────────────────
install_packages() {
    log "Updating package lists..."
    apt-get update -qq

    log "Installing curl, unzip, rsync, nginx..."
    apt-get install -y -qq curl unzip rsync nginx ca-certificates gnupg
}

# ──────────────────────────────────────────────
# Step 2 — Docker & Docker Compose
# ──────────────────────────────────────────────
install_docker() {
    if command -v docker &>/dev/null; then
        log "Docker is already installed ($(docker --version))."
    else
        log "Installing Docker via official convenience script..."
        curl -fsSL https://get.docker.com | bash
    fi

    # Ensure the docker service is enabled and running
    systemctl enable --now docker

    # Install Docker Compose plugin if missing
    if docker compose version &>/dev/null; then
        log "Docker Compose plugin is already installed."
    else
        log "Installing Docker Compose plugin..."
        apt-get install -y -qq docker-compose-plugin
    fi

    # Add the calling user to the docker group (if run via sudo)
    if [[ -n "${SUDO_USER:-}" ]]; then
        if ! groups "$SUDO_USER" | grep -q '\bdocker\b'; then
            log "Adding user '${SUDO_USER}' to docker group..."
            usermod -aG docker "$SUDO_USER"
            warn "Log out and back in (or run 'newgrp docker') for group changes to take effect."
        fi
    fi
}

# ──────────────────────────────────────────────
# Step 3 — Directory structure
# ──────────────────────────────────────────────
create_directories() {
    log "Creating application directories..."
    mkdir -p "$INSTALL_DIR"
    mkdir -p "$BACKUP_DIR"
    mkdir -p /opt/apps

    # Allow the sudo user to own the dirs for easier management
    if [[ -n "${SUDO_USER:-}" ]]; then
        chown -R "${SUDO_USER}:${SUDO_USER}" /opt/apps
    fi

    log "  ${INSTALL_DIR}"
    log "  ${BACKUP_DIR}"
}

# ──────────────────────────────────────────────
# Step 4 — Nginx reverse proxy
# ──────────────────────────────────────────────
configure_nginx() {
    log "Configuring Nginx reverse proxy..."

    cat > "$NGINX_CONF" <<'NGINX'
# School Supply Inventory — Nginx Reverse Proxy
# Generated by rpi-setup.sh

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Max upload size (for potential future file uploads)
    client_max_body_size 10M;

    # API — proxy to FastAPI backend
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Swagger / OpenAPI docs
    location /docs {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /openapi.json {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
    }

    # Health check endpoint
    location /health {
        proxy_pass http://127.0.0.1:8000;
    }

    # Frontend — proxy to Vue/Vuetify SPA
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
NGINX

    # Enable the site
    rm -f /etc/nginx/sites-enabled/default
    ln -sf "$NGINX_CONF" "$NGINX_LINK"

    # Test and reload
    nginx -t || fail "Nginx configuration test failed."
    systemctl enable --now nginx
    systemctl reload nginx

    log "Nginx configured and running."
}

# ──────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────
print_summary() {
    echo ""
    echo "════════════════════════════════════════════════════════"
    log "Raspberry Pi setup complete!"
    echo "════════════════════════════════════════════════════════"
    echo ""
    echo "  Installed:"
    echo "    - curl $(curl --version | head -1 | awk '{print $2}')"
    echo "    - unzip $(unzip -v 2>&1 | head -1 | awk '{print $2}')"
    echo "    - $(docker --version)"
    echo "    - Docker Compose $(docker compose version --short 2>/dev/null || echo 'unknown')"
    echo "    - nginx $(nginx -v 2>&1 | cut -d/ -f2)"
    echo ""
    echo "  Directories:"
    echo "    - ${INSTALL_DIR}   (application)"
    echo "    - ${BACKUP_DIR}    (database backups)"
    echo ""
    echo "  Nginx:"
    echo "    - Config: ${NGINX_CONF}"
    echo "    - Proxies port 80 → frontend (8080) + backend (8000)"
    echo ""
    echo "  Next steps:"
    echo "    1. Run the deploy script to install the application:"
    echo "       sudo ${INSTALL_DIR}/scripts/deploy.sh"
    echo "       — or if not yet deployed —"
    echo "       curl -fsSL https://raw.githubusercontent.com/terickson/school-inventory/main/scripts/deploy.sh | sudo bash"
    echo ""
    echo "    2. After deploy, access the app at:"
    echo "       http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'your-pi-ip')"
    echo ""
}

# ──────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────
main() {
    require_root
    log "Starting Raspberry Pi setup for School Supply Inventory..."
    echo ""

    install_packages
    install_docker
    create_directories
    configure_nginx
    print_summary
}

main
